/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CourseMarket } from "./CourseMarket";
export type { MMCERC721Coin } from "./MMCERC721Coin";
export type { MMCToken } from "./MMCToken";
export type { MockOracle } from "./MockOracle";
