// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint:
        "https://osrd32f43jehvo65qvyfkk5jsi.appsync-api.us-east-2.amazonaws.com/graphql",
      region: "us-east-2",
      defaultAuthMode: "apiKey",
      apiKey: "da2-tzqbhbbedzh2hbtmnyfykr4yo4",
    },
  },
};

export default config;
